from openai import OpenAI

from opentelemetry import trace, metrics
from opentelemetry.sdk.resources import Resource

from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter

from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.exporter.otlp.proto.http.metric_exporter import OTLPMetricExporter


# =========================
# OTEL CONFIG
# =========================
SERVICE_NAME = "local-ollama-phi3"
TRACE_ENDPOINT = "http://localhost:4318/v1/traces"
METRIC_ENDPOINT = "http://localhost:4318/v1/metrics"

resource = Resource.create({"service.name": SERVICE_NAME})


# =========================
# OTEL TRACE SETUP
# =========================
trace_provider = TracerProvider(resource=resource)

trace_exporter = OTLPSpanExporter(
    endpoint=TRACE_ENDPOINT,
    timeout=30,
)

trace_processor = BatchSpanProcessor(
    trace_exporter,
    schedule_delay_millis=500,
    max_export_batch_size=32,
    max_queue_size=256,
)

trace_provider.add_span_processor(trace_processor)
trace.set_tracer_provider(trace_provider)
tracer = trace.get_tracer(__name__)


# =========================
# OTEL METRICS SETUP
# =========================
metric_exporter = OTLPMetricExporter(
    endpoint=METRIC_ENDPOINT,
    timeout=30,
)

metric_reader = PeriodicExportingMetricReader(
    metric_exporter,
    export_interval_millis=5000,
)

meter_provider = MeterProvider(
    resource=resource,
    metric_readers=[metric_reader],
)

metrics.set_meter_provider(meter_provider)
meter = metrics.get_meter(__name__)


# =========================
# CUSTOM LLM METRICS
# =========================
prompt_tokens_counter = meter.create_counter(
    "llm.prompt.tokens",
    description="Number of prompt/input tokens used by the LLM",
    unit="tokens",
)

completion_tokens_counter = meter.create_counter(
    "llm.completion.tokens",
    description="Number of completion/output tokens generated by the LLM",
    unit="tokens",
)

total_tokens_counter = meter.create_counter(
    "llm.total.tokens",
    description="Total number of LLM tokens used",
    unit="tokens",
)

prompt_cost_counter = meter.create_counter(
    "llm.prompt.cost.usd",
    description="Estimated prompt/input token cost in USD",
    unit="USD",
)

completion_cost_counter = meter.create_counter(
    "llm.completion.cost.usd",
    description="Estimated completion/output token cost in USD",
    unit="USD",
)

total_cost_counter = meter.create_counter(
    "llm.total.cost.usd",
    description="Estimated total LLM cost in USD",
    unit="USD",
)


# =========================
# OLLAMA CONFIG
# =========================
client = OpenAI(
    base_url="http://localhost:11434/v1",
    api_key="ollama",
)

chat_history = []


# =========================
# COST CONFIG
# =========================
# Local Ollama has no API billing cost.
# You can change these later when testing OpenAI / Claude / paid models.
INPUT_COST_PER_1M_TOKENS = 0.00
OUTPUT_COST_PER_1M_TOKENS = 0.00


def get_usage(response):
    usage = getattr(response, "usage", None)

    prompt_tokens = getattr(usage, "prompt_tokens", 0) if usage else 0
    completion_tokens = getattr(usage, "completion_tokens", 0) if usage else 0
    total_tokens = getattr(usage, "total_tokens", prompt_tokens + completion_tokens) if usage else prompt_tokens + completion_tokens

    return prompt_tokens, completion_tokens, total_tokens


def ask_phi3(prompt: str) -> str:
    model = "phi3:mini"
    temperature = 0
    max_tokens = 100

    chat_history.append({"role": "user", "content": prompt})

    metric_attrs = {
        "llm.model": model,
        "llm.provider": "ollama",
        "environment": "local",
        "service.name": SERVICE_NAME,
    }

    with tracer.start_as_current_span("ollama-chat-request") as span:
        span.set_attribute("llm.provider", "ollama")
        span.set_attribute("llm.model", model)
        span.set_attribute("llm.prompt", prompt)
        span.set_attribute("llm.temperature", temperature)
        span.set_attribute("llm.max_tokens", max_tokens)

        try:
            response = client.chat.completions.create(
                model=model,
                messages=chat_history,
                temperature=temperature,
                max_tokens=max_tokens,
            )

            answer = response.choices[0].message.content
            chat_history.append({"role": "assistant", "content": answer})

            prompt_tokens, completion_tokens, total_tokens = get_usage(response)

            prompt_cost = (prompt_tokens / 1_000_000) * INPUT_COST_PER_1M_TOKENS
            completion_cost = (completion_tokens / 1_000_000) * OUTPUT_COST_PER_1M_TOKENS
            total_cost = prompt_cost + completion_cost

            span.set_attribute("llm.response", answer)
            span.set_attribute("llm.prompt.tokens", prompt_tokens)
            span.set_attribute("llm.completion.tokens", completion_tokens)
            span.set_attribute("llm.total.tokens", total_tokens)
            span.set_attribute("llm.prompt.cost.usd", prompt_cost)
            span.set_attribute("llm.completion.cost.usd", completion_cost)
            span.set_attribute("llm.total.cost.usd", total_cost)
            span.set_attribute("status", "success")

            prompt_tokens_counter.add(prompt_tokens, metric_attrs)
            completion_tokens_counter.add(completion_tokens, metric_attrs)
            total_tokens_counter.add(total_tokens, metric_attrs)

            prompt_cost_counter.add(prompt_cost, metric_attrs)
            completion_cost_counter.add(completion_cost, metric_attrs)
            total_cost_counter.add(total_cost, metric_attrs)

            return answer

        except Exception as e:
            span.set_attribute("status", "error")
            span.set_attribute("error.type", type(e).__name__)
            span.set_attribute("error.message", str(e))
            raise


if __name__ == "__main__":
    print("\nLocal AI Chat - Splunk OTEL Test")
    print("Type your question and press Enter.")
    print("Type 'quit', 'exit', or 'q' when you are done.\n")

    try:
        while True:
            user_input = input("You: ").strip()

            if user_input.lower() in ["quit", "exit", "q", "done"]:
                print("\nDone. Ending chat.")
                break

            if not user_input:
                print("Please type a question, or type 'quit' to exit.\n")
                continue

            result = ask_phi3(user_input)
            print(f"AI: {result}\n")

    finally:
        trace_provider.force_flush(timeout_millis=30000)
        meter_provider.force_flush(timeout_millis=30000)

        trace_provider.shutdown()
        meter_provider.shutdown()