import os
import time
import uuid
from pathlib import Path
from typing import List, Dict, Any

import chromadb
import requests
from pypdf import PdfReader
from openai import OpenAI

from opentelemetry import trace, metrics
from opentelemetry.sdk.resources import Resource

from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter

from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.exporter.otlp.proto.http.metric_exporter import OTLPMetricExporter


# =========================
# CONFIG
# =========================
SERVICE_NAME = "local-rag-phi3"
ENVIRONMENT = "local"

OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_OPENAI_BASE_URL = "http://localhost:11434/v1"

EMBED_MODEL = "nomic-embed-text"
GEN_MODEL = "phi3:mini"

PDF_DIR = Path("./rag-pdfs")
CHROMA_DIR = Path("./chroma-rag-db")
COLLECTION_NAME = "local_pdf_rag"

TOP_K = 4
CHUNK_SIZE = 900
CHUNK_OVERLAP = 150

TRACE_ENDPOINT = "http://localhost:4318/v1/traces"
METRIC_ENDPOINT = "http://localhost:4318/v1/metrics"


# =========================
# OTEL SETUP
# =========================
resource = Resource.create(
    {
        "service.name": SERVICE_NAME,
        "deployment.environment": ENVIRONMENT,
        "llm.provider": "ollama",
        "llm.model": GEN_MODEL,
        "embedding.model": EMBED_MODEL,
    }
)

trace_provider = TracerProvider(resource=resource)

trace_exporter = OTLPSpanExporter(
    endpoint=TRACE_ENDPOINT,
    timeout=30,
)

trace_processor = BatchSpanProcessor(
    trace_exporter,
    schedule_delay_millis=500,
    max_export_batch_size=32,
    max_queue_size=256,
)

trace_provider.add_span_processor(trace_processor)
trace.set_tracer_provider(trace_provider)
tracer = trace.get_tracer(__name__)

metric_exporter = OTLPMetricExporter(
    endpoint=METRIC_ENDPOINT,
    timeout=30,
)

metric_reader = PeriodicExportingMetricReader(
    metric_exporter,
    export_interval_millis=5000,
)

meter_provider = MeterProvider(
    resource=resource,
    metric_readers=[metric_reader],
)

metrics.set_meter_provider(meter_provider)
meter = metrics.get_meter(__name__)


retrieval_latency_counter = meter.create_counter(
    "llm.rag.retrieval.latency.ms",
    unit="ms",
    description="Total retrieval latency in milliseconds",
)

embedding_latency_counter = meter.create_counter(
    "llm.rag.embedding.latency.ms",
    unit="ms",
    description="Embedding latency in milliseconds",
)

generation_latency_counter = meter.create_counter(
    "llm.rag.generation.latency.ms",
    unit="ms",
    description="Generation latency in milliseconds",
)

prompt_tokens_counter = meter.create_counter(
    "llm.rag.prompt.tokens",
    unit="tokens",
    description="Prompt tokens used by RAG generation",
)

completion_tokens_counter = meter.create_counter(
    "llm.rag.completion.tokens",
    unit="tokens",
    description="Completion tokens generated by RAG generation",
)

total_tokens_counter = meter.create_counter(
    "llm.rag.total.tokens",
    unit="tokens",
    description="Total tokens used by RAG generation",
)

retrieved_chunks_counter = meter.create_counter(
    "llm.rag.retrieved.chunks",
    unit="1",
    description="Number of chunks retrieved per RAG request",
)


# =========================
# CLIENTS
# =========================
llm_client = OpenAI(
    base_url=OLLAMA_OPENAI_BASE_URL,
    api_key="ollama",
)

chroma_client = chromadb.PersistentClient(path=str(CHROMA_DIR))
collection = chroma_client.get_or_create_collection(name=COLLECTION_NAME)


# =========================
# PDF + CHUNKING
# =========================
def read_pdf_text(pdf_path: Path) -> str:
    reader = PdfReader(str(pdf_path))
    pages = []

    for page in reader.pages:
        text = page.extract_text() or ""
        if text.strip():
            pages.append(text)

    return "\n".join(pages)


def chunk_text(text: str, chunk_size: int = CHUNK_SIZE, overlap: int = CHUNK_OVERLAP) -> List[str]:
    text = " ".join(text.split())
    chunks = []

    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end].strip()

        if chunk:
            chunks.append(chunk)

        start += chunk_size - overlap

    return chunks


# =========================
# EMBEDDING
# =========================
def embed_text(text: str) -> List[float]:
    response = requests.post(
        f"{OLLAMA_BASE_URL}/api/embeddings",
        json={
            "model": EMBED_MODEL,
            "prompt": text,
        },
        timeout=60,
    )
    response.raise_for_status()

    data = response.json()
    return data["embedding"]


# =========================
# INDEXING
# =========================
def index_pdfs() -> None:
    pdf_files = sorted(PDF_DIR.glob("*.pdf"))

    if len(pdf_files) < 5:
        print(f"WARNING: Found only {len(pdf_files)} PDFs in {PDF_DIR}. Add 5 PDFs for the demo.")

    print(f"\nIndexing PDFs from: {PDF_DIR.resolve()}")
    print(f"Found {len(pdf_files)} PDF files.\n")

    for pdf_path in pdf_files:
        print(f"Reading: {pdf_path.name}")
        text = read_pdf_text(pdf_path)
        chunks = chunk_text(text)

        print(f"  Chunks: {len(chunks)}")

        for i, chunk in enumerate(chunks):
            chunk_id = f"{pdf_path.stem}-{i}-{uuid.uuid4().hex[:8]}"

            embedding = embed_text(chunk)

            collection.add(
                ids=[chunk_id],
                embeddings=[embedding],
                documents=[chunk],
                metadatas=[
                    {
                        "source": pdf_path.name,
                        "chunk_index": i,
                    }
                ],
            )

    print("\nIndexing complete.")


# =========================
# RAG QUERY
# =========================
def estimate_tokens(text: str) -> int:
    return max(1, len(text.split()))


def get_usage(response: Any, fallback_prompt: str, fallback_answer: str):
    usage = getattr(response, "usage", None)

    if usage:
        prompt_tokens = getattr(usage, "prompt_tokens", 0) or 0
        completion_tokens = getattr(usage, "completion_tokens", 0) or 0
        total_tokens = getattr(usage, "total_tokens", prompt_tokens + completion_tokens) or 0
    else:
        prompt_tokens = estimate_tokens(fallback_prompt)
        completion_tokens = estimate_tokens(fallback_answer)
        total_tokens = prompt_tokens + completion_tokens

    return prompt_tokens, completion_tokens, total_tokens


def rag_answer(question: str) -> str:
    attrs = {
        "service.name": SERVICE_NAME,
        "llm.model": GEN_MODEL,
        "llm.provider": "ollama",
        "embedding.model": EMBED_MODEL,
        "environment": ENVIRONMENT,
    }

    with tracer.start_as_current_span("rag-query") as parent_span:
        parent_span.set_attribute("rag.question", question)
        parent_span.set_attribute("rag.top_k", TOP_K)
        parent_span.set_attribute("llm.model", GEN_MODEL)
        parent_span.set_attribute("embedding.model", EMBED_MODEL)

        # -------------------------
        # Child span 1: embed
        # -------------------------
        with tracer.start_as_current_span("embed") as embed_span:
            embed_start = time.perf_counter()
            query_embedding = embed_text(question)
            embed_latency_ms = (time.perf_counter() - embed_start) * 1000

            embed_span.set_attribute("embedding.model", EMBED_MODEL)
            embed_span.set_attribute("embedding.latency.ms", embed_latency_ms)
            embedding_latency_counter.add(embed_latency_ms, attrs)

        # -------------------------
        # Child span 2: retrieve
        # -------------------------
        with tracer.start_as_current_span("retrieve") as retrieve_span:
            retrieve_start = time.perf_counter()

            results = collection.query(
                query_embeddings=[query_embedding],
                n_results=TOP_K,
                include=["documents", "metadatas", "distances"],
            )

            retrieval_latency_ms = (time.perf_counter() - retrieve_start) * 1000

            docs = results.get("documents", [[]])[0]
            metadatas = results.get("metadatas", [[]])[0]
            distances = results.get("distances", [[]])[0]

            retrieve_span.set_attribute("rag.retrieval.latency.ms", retrieval_latency_ms)
            retrieve_span.set_attribute("rag.retrieved.count", len(docs))

            if distances:
                retrieve_span.set_attribute("rag.top_distance", float(distances[0]))

            sources = []
            for meta in metadatas:
                if meta and "source" in meta:
                    sources.append(str(meta["source"]))

            retrieve_span.set_attribute("rag.sources", ",".join(sorted(set(sources))))

            retrieval_latency_counter.add(retrieval_latency_ms, attrs)
            retrieved_chunks_counter.add(len(docs), attrs)

        context = "\n\n".join(
            [
                f"Source: {metadatas[i].get('source', 'unknown')}\n{docs[i]}"
                for i in range(len(docs))
            ]
        )

        generation_prompt = f"""
You are a helpful assistant. Answer the question using only the context below.

Context:
{context}

Question:
{question}

Answer:
""".strip()

        # -------------------------
        # Child span 3: generate
        # -------------------------
        with tracer.start_as_current_span("generate") as generate_span:
            generate_start = time.perf_counter()

            response = llm_client.chat.completions.create(
                model=GEN_MODEL,
                messages=[
                    {"role": "user", "content": generation_prompt},
                ],
                temperature=0,
                max_tokens=250,
            )

            generation_latency_ms = (time.perf_counter() - generate_start) * 1000

            answer = response.choices[0].message.content or ""

            prompt_tokens, completion_tokens, total_tokens = get_usage(
                response=response,
                fallback_prompt=generation_prompt,
                fallback_answer=answer,
            )

            generate_span.set_attribute("llm.model", GEN_MODEL)
            generate_span.set_attribute("llm.prompt.tokens", prompt_tokens)
            generate_span.set_attribute("llm.completion.tokens", completion_tokens)
            generate_span.set_attribute("llm.total.tokens", total_tokens)
            generate_span.set_attribute("llm.generation.latency.ms", generation_latency_ms)
            generate_span.set_attribute("llm.response", answer)

            generation_latency_counter.add(generation_latency_ms, attrs)
            prompt_tokens_counter.add(prompt_tokens, attrs)
            completion_tokens_counter.add(completion_tokens, attrs)
            total_tokens_counter.add(total_tokens, attrs)

        parent_span.set_attribute("status", "success")

        return answer


# =========================
# CLI
# =========================
def main():
    print("\nLocal RAG over PDFs - Splunk OTEL")
    print("Commands:")
    print("  index  - index PDFs from ./rag-pdfs")
    print("  ask    - ask questions over indexed PDFs")
    print("  quit   - exit\n")

    while True:
        command = input("Command [index/ask/quit]: ").strip().lower()

        if command in ["quit", "exit", "q"]:
            break

        if command == "index":
            index_pdfs()
            continue

        if command == "ask":
            while True:
                question = input("\nQuestion: ").strip()

                if question.lower() in ["back", "quit", "exit", "q"]:
                    break

                if not question:
                    continue

                try:
                    answer = rag_answer(question)
                    print(f"\nAnswer:\n{answer}\n")
                except Exception as exc:
                    print(f"ERROR: {type(exc).__name__}: {exc}")

            continue

        print("Unknown command. Use index, ask, or quit.")

    trace_provider.force_flush(timeout_millis=30000)
    meter_provider.force_flush(timeout_millis=30000)
    trace_provider.shutdown()
    meter_provider.shutdown()


if __name__ == "__main__":
    main()